### ISSUE TITLE
`gh_org` input format for `generateReport` function

### ISSUE THREAD

**Issue by shbrief** [Bioconductor/BiocPkgStats#1]
For the `gh_org` argument, I provided the character vector with the same length as the `packages` input. But I received this error message:

```
Error in generateReport(packages = packages, gh_org = gh_org, since_date = since_date,  : 
  BiocBaseUtils::isScalarCharacter(gh_org) is not TRUE
```

Can you help me to resolve this? Thanks!

**Comment by LiNk-NY** [comment]
It should be fixed here: 5301a5b2ecda67e1f52bc01319ba962867c6b2b9
Thanks
