### ISSUE TITLE
`generateReport` can't find the package?

### ISSUE THREAD

**Issue by shbrief** [Bioconductor/BiocPkgStats#2]
Can `generateReport` extract information only for specific types of packages (e.g. software packages)? I applied this function on over a dozen packages, and only a few worked. Here is an example:

```
> generateReport(packages = "MultiAssayExperiment", gh_org = "waldronlab", since_date <- "2019-09-01", outdir = ".")
> generateReport(packages = "curatedTCGAData", gh_org = "waldronlab", since_date <- "2019-09-01", outdir = ".")
Error in utils::packageDescription(pkg = package)$biocViews : 
  $ operator is invalid for atomic vectors
In addition: Warning message:
In utils::packageDescription(pkg = package) :
  no package 'curatedTCGAData' was found
```

**Comment by LiNk-NY** [comment]
@shbrief They have to be installed before you can check their `DESCRIPTION` file. I will make a note of that in the documentation.

**Comment by LiNk-NY** [comment]
see here: fd24740f42fe964bc4979f9c7a48d05711bb6ebc
